CREATE TABLE chat_messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id   BIGINT,
    chat_id      BIGINT                              NOT NULL,
    group_name   TEXT                                NOT NULL,
    sender_id    BIGINT                              NOT NULL,
    message_text TEXT,
    urls         TEXT[],
    timestamp    TIMESTAMPTZ                         NOT NULL,
    CONSTRAINT chat_messages_pk PRIMARY KEY (id)
);


CREATE TABLE channel_news
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id   BIGINT,
    chat_id      BIGINT                              NOT NULL,
    group_name   TEXT                                NOT NULL,
    message_text TEXT,
    urls         TEXT[],
    timestamp    TIMESTAMPTZ                         NOT NULL,
    CONSTRAINT channel_news_pk PRIMARY KEY (id)
);

CREATE TABLE link_content
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    related_super_group_id BIGINT,
    url                    TEXT,
    title                  TEXT,
    content                TEXT,
    timestamp              TIMESTAMPTZ                         NOT NULL,
    CONSTRAINT link_content_pk PRIMARY KEY (id)
);

CREATE TABLE config
(
    id        int GENERATED ALWAYS AS IDENTITY NOT NULL,
    "version" varchar                          NOT NULL,
    config    json                             NOT NULL,
    CONSTRAINT config_pk PRIMARY KEY (id),
    CONSTRAINT config_unique UNIQUE ("version")
);

----------------------------------------------------------------------

CREATE TABLE message_summary
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_count INT         NOT NULL,
    start_time    TIMESTAMPTZ NOT NULL,
    end_time      TIMESTAMPTZ NOT NULL
);

-- 每个 symbol 出现的次数
CREATE TABLE related_symbol_count
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    summary_id BIGINT NOT NULL,
    symbol     TEXT   NOT NULL,
    count      INT    NOT NULL,
    UNIQUE (summary_id, symbol)
);


-- 每个 symbol 在不同情绪下的次数
CREATE TABLE market_sentiment_count
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    summary_id BIGINT           NOT NULL,
    symbol     TEXT             NOT NULL,
    sentiment  INT              NOT NULL,  -- 1: positive, 0: neutral, -1: negative
    count      INT              NOT NULL,
    UNIQUE (summary_id, symbol, sentiment)
);