CREATE TABLE chat_messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id   BIGINT,
    chat_id      BIGINT                              NOT NULL,
    group_name   TEXT                                NOT NULL,
    sender_id    BIGINT                              NOT NULL,
    message_text TEXT,
    urls         TEXT[],
    timestamp    TIMESTAMPTZ                         NOT NULL,
    CONSTRAINT chat_messages_pk PRIMARY KEY (id)
);

CREATE INDEX idx_chat_messages_chatid_senderid ON chat_messages (chat_id, sender_id);
CREATE UNIQUE INDEX idx_chat_message_unique ON chat_messages (chat_id, message_id);

CREATE TABLE channel_news
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id   BIGINT,
    chat_id      BIGINT                              NOT NULL,
    group_name   TEXT                                NOT NULL,
    message_text TEXT,
    urls         TEXT[],
    timestamp    TIMESTAMPTZ                         NOT NULL,
    CONSTRAINT channel_news_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_channel_news_unique ON channel_news (chat_id, message_id);

CREATE TABLE link_content
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    related_super_group_id BIGINT,
    url                    TEXT,
    title                  TEXT,
    content                TEXT,
    timestamp              TIMESTAMPTZ                         NOT NULL,
    CONSTRAINT link_content_pk PRIMARY KEY (id)
);

CREATE TABLE related_symbol
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id     BIGINT                                  NOT NULL,
    group_name  TEXT                                    NOT NULL,
    message_id  BIGINT,
    symbol      TEXT                                    NOT NULL,
    source_type INT                                     NOT NULL, -- 0: chat, 1: channel_news
    timestamp   TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT related_symbol_pk PRIMARY KEY (id)
);

CREATE TABLE config
(
    id        int GENERATED ALWAYS AS IDENTITY NOT NULL,
    "version" varchar                          NOT NULL,
    config    json                             NOT NULL,
    CONSTRAINT config_pk PRIMARY KEY (id),
);
CREATE UNIQUE INDEX config_unique ON channel_news ("version");

CREATE TABLE config_impressions
(
    id          int GENERATED ALWAYS AS IDENTITY NOT NULL,
    source_type INT                              NOT NULL, -- 0: chat, 1: channel_news
    chat_id     BIGINT                           NOT NULL
);

CREATE TABLE impression
(
    id          int GENERATED ALWAYS AS IDENTITY NOT NULL,
    related_id  BIGINT                           NOT NULL, -- chat_messages.id or channel_news.id
    source_type INT                              NOT NULL, -- 0: chat, 1: channel_news
    chat_id     BIGINT                           NOT NULL,
    group_name  TEXT                             NOT NULL,
    views       INT                              NOT NULL DEFAULT 0,
    internal    TEXT                             NOT NULL,
    timestamp   TIMESTAMPTZ                      NOT NULL,
    CONSTRAINT impression_pk PRIMARY KEY (id)
);


CREATE TABLE message_summary
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id       BIGINT         NOT NULL,
    message_count INT         NOT NULL,
    start_time    TIMESTAMPTZ NOT NULL,
    end_time      TIMESTAMPTZ NOT NULL
);

-- 每个 symbol 出现的次数
CREATE TABLE related_symbol_count
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    summary_id BIGINT NOT NULL,
    symbol     TEXT   NOT NULL,
    count      INT    NOT NULL,
);
CREATE UNIQUE INDEX summary_symbol_unique ON channel_news ("summary_id", "symbol");

-- 每个 symbol 在不同情绪下的次数
CREATE TABLE market_sentiment_count
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    summary_id BIGINT           NOT NULL,
    symbol     TEXT             NOT NULL,
    sentiment  INT              NOT NULL,  -- 1: positive, 0: neutral, -1: negative
    count      INT              NOT NULL,
);
CREATE UNIQUE INDEX summary_symbol_sentiment_unique ON channel_news ("summary_id", "symbol", "sentiment");